### ISSUE TITLE
Exception when handling incoming emoji

### ISSUE THREAD

**Issue by thomotron** [thomotron/Rolly#3]
Rolly was on a long-running streak from October 8 without many hiccups (aside from name matching, being fixed in 83a396ee7531657f01d19a9de93cd0d200067561). Might have been an API change.

Discord.py version: `1.1.1`

```
Task exception was never retrieved                                                                                                                    
future: <Task finished coro=<Client.run.<locals>.runner() done, defined at /home/tom/.local/lib/python3.7/site-packages/discord/client.py:545> exception=KeyError('animated')>               
Traceback (most recent call last):                                                                                                                      File "/home/tom/.local/lib/python3.7/site-packages/discord/client.py", line 547, in runner
    await self.start(*args, **kwargs)                                                                                                                   File "/home/tom/.local/lib/python3.7/site-packages/discord/client.py", line 511, in start                                                           
    await self.connect(reconnect=reconnect)                                                                                                             File "/home/tom/.local/lib/python3.7/site-packages/discord/client.py", line 433, in connect
    await self._connect()                                                                                                                               File "/home/tom/.local/lib/python3.7/site-packages/discord/client.py", line 397, in _connect
    await self.ws.poll_event()                                                                                                                          File "/home/tom/.local/lib/python3.7/site-packages/discord/gateway.py", line 470, in poll_event                                                     
    await self.received_message(msg)                                                                                                                    File "/home/tom/.local/lib/python3.7/site-packages/discord/gateway.py", line 424, in received_message
    func(data)                                                                                                                                          File "/home/tom/.local/lib/python3.7/site-packages/discord/state.py", line 410, in parse_message_reaction_add
    emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated' 
```

**Comment by thomotron** [comment]
Check if this can be reproduced by using an animated emote on the roll call message

**Comment by thomotron** [comment]
Unable to reproduce this on the latest version.
